name: Publish release
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read version numbers from .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          quiet: true
      - name: Zip datapack directory
        run: |
          mkdir -p dist
          cd datapack && zip -r "../dist/gallop-gauge-dp-${{ env.DATAPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip" ./*
      - name: Zip resourcepack directory
        run: |
          cd resourcepack && zip -r "../dist/gallop-gauge-rp-${{ env.RESOURCEPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip" ./*

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          checksumGenerateAssets: 'false'
          assets: |
            - path: ./dist/gallop-gauge-dp-${{ env.DATAPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip
              label: Datapack
            - path: ./dist/rp-gallop-gauge-rp-${{ env.RESOURCEPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip
              label: Resource Pack
