name: Publish release
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read version numbers from .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          quiet: true
      - name: Zip datapack directory
        run: |
          mkdir -p dist
          zip -r "dist/dp-gallop-gauge-${{ env.DATAPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip" datapack
      - name: Zip resourcepack directory
        run: |
          zip -r "dist/rp-gallop-gauge-${{ env.RESOURCEPACK_VERSION }}_mc_v${{ env.MC_VERSION }}.zip" resourcepack

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: ./dist/*.zip
